"""rename address

Revision ID: 184632883f56
Revises: ec4ca6601ce9
Create Date: 2024-06-30 14:54:36.226158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184632883f56'
down_revision = 'ec4ca6601ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
