"""rename department

Revision ID: ec4ca6601ce9
Revises: 27bf8e74cff6
Create Date: 2024-06-30 14:48:37.234384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4ca6601ce9'
down_revision = '27bf8e74cff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
